admin_password="Welcome123$"
key_name="cloudwatchtest"
vpc_subnet_id= "subnet-013e4448"
iam_role="AmazonEC2RoleforSSM"
s3_bucket_name="cloudwatch-logs-from-ec2-prototype"
s3_aws_region="us-west-2"
aws_vpc_id=""
